{
 "title": "Boot.Metrics Impostor Dashboard",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "server_name",
    "query": {
     "query": "label_values(process_memory_usage_bytes,server_name)"
    }
   }
  ]
 },
 "panels": [
  { "title": "System Resources", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Memory",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 10, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "process_memory_usage_bytes{server_name=~\"$server_name\"}",
     "legendFormat": "{{server_name}}"
    }
   ]
  },
  {
   "title": "CPU",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 10, "x": 10, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum by(server_name) (irate(process_cpu_time_seconds{server_name=~\"$server_name\"}[1m]))",
     "legendFormat": "{{server_name}}"
    },
    {
     "expr": "sum by(server_name) (irate(process_cpu_time_seconds_total{server_name=~\"$server_name\"}[1m]))",
     "legendFormat": "{{server_name}}"
    }
   ]
  },
  {
   "title": "CPU Average",
   "type": "histogram",
   "gridPos": { "h": 7, "w": 4, "x": 20, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum by(server_name) (rate(process_cpu_time_seconds{server_name=~\"$server_name\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum by(server_name) (rate(process_cpu_time_seconds_total{server_name=~\"$server_name\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Client statistics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 } },
  {
   "title": "Connected Clients",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "sum by(server_name) (boot_metrics_clients_connected{server_name=~\"$server_name\"})",
     "legendFormat": "{{ server_name }}"
    }
   ]
  },
  {
   "title": "Clients by version",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 4, "x": 12, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(game_version) (boot_metrics_clients_total{server_name=~\"$server_name\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Clients by platform",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 4, "x": 16, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(platform) (boot_metrics_clients_total{server_name=~\"$server_name\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Clients by language",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 4, "x": 20, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(language) (boot_metrics_clients_total{server_name=~\"$server_name\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Game statistics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 } },
  {
   "title": "Rooms",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
   "targets": [
    {
     "expr": "sum by(server_name) (boot_metrics_games_open{server_name=~\"$server_name\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Lobbies by Map",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 4, "x": 12, "y": 18 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(map) (boot_metrics_games_total{server_name=~\"$server_name\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Lobbies by Public state",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 4, "x": 16, "y": 18 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(public) (boot_metrics_games_total{server_name=~\"$server_name\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Lobbies by Game Mode",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 4, "x": 20, "y": 18 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(game_mode) (boot_metrics_games_total{server_name=~\"$server_name\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Rooms",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 26 },
   "targets": [
    {
     "expr": "sum by(game_state) (boot_metrics_games_open{server_name=~\"$server_name\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Rooms by player count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 26 },
   "targets": [
    {
     "expr": "sum by(player_count) (boot_metrics_games_open{server_name=~\"$server_name\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Amount of exceptions",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 34 },
   "targets": [
    {
     "expr": "process_runtime_dotnet_exceptions_count{server_name=~\"$server_name\"}",
     "legendFormat": "{{server_name}}"
    },
    {
     "expr": "process_runtime_dotnet_exceptions_count_total{server_name=~\"$server_name\"}",
     "legendFormat": "{{server_name}}"
    }
   ]
  }
 ]
}